### ISSUE TITLE
bash: rbenv: command not found

### ISSUE THREAD

**Issue by phawk** [leucos/ansible-rbenv-playbook#3]
Hey, trying to use this role and getting to the step `TASK: [rbenv-ruby | Installs ruby]` and failing with the following error:

```
failed: [178.62.114.246] => {"ansible_job_id": "763143692762.11188", "changed": true, "cmd": "cd; bash -lc \"MAKEOPTS= CONFIGURE_OPTS=--disable-install-rdoc rbenv install 2.1.5\"", "delta": "0:00:00.020467", "end": "2015-01-01 17:07:01.720530", "finished": 1, "rc": 127, "start": "2015-01-01 17:07:01.700063"}
stderr: bash: rbenv: command not found
<job 763143692762.11188> FAILED on 178.62.114.246

FATAL: all hosts have already failed -- aborting
```

Any ideas what’s up?

I’m running ansible version 1.7.1 on Mac OSX Yosemite. I’m trying to run this against a Ubuntu 14.04 x64 server on digital ocean. Please let me know if you need any more info about my environment.

I am running the command `ansible-playbook -i hosts rails_deploy.yml`

[This Gist](https://gist.github.com/phawk/8b16e08970472f45a7f0) will show you my configuration and that I am SSHing to the box with sudo and a user named 'deploy' which is also the ssh user the rbenv commands are run as.

**Comment by leucos** [comment]
Thanks for the heads up @phawk . Note this playbook is quite old.
I will post something more up to date RSN. I'll poke you here when it's done.

**Comment by phawk** [comment]
@leucos thanks, I got it working eventually but I have referenced the full path to the `rbenv` binary. I’ve been using this for [Rails deploy](https://github.com/phawk/rails-deploy) a set of ansible scripts to provision a working rails server. If you manage to get it working better I could link this role in as a git submodule to keep things up to date.

**Comment by leucos** [comment]
Note that this playbook is now superseded by this one : https://github.com/erasme/ansible-rbenv (erasme.rbenv on galaxy).
